### ISSUE TITLE
About the pretrained model

### ISSUE THREAD

**Issue by sunnyHelen** [zehuichen123/BEVDistill#3]
Hi, thanks a lot for sharing your code. I find that the student model is trained from a pre-trained model "data/pretrain_models/fcos3d_r50_new.pth". Can you provide it, or tell us how to get it?

Thank you very much.

**Comment by zehuichen123** [comment]
Hi, this is just an FCOS3D r50 pretrain, and we simply replace all `backbone` to `img_backbone` in its params. We will update the pretrain models in the readme.

**Comment by sunnyHelen** [comment]
Thanks. That's very helpful.
